### ISSUE TITLE
Predict checkout/return ratio for station hourly 

### ISSUE THREAD

**Issue by CharlesG12** [jefwang9/733_Final_Project#10]

**Comment by CharlesG12** [comment]
add feature: weather

**Comment by yukewang1** [comment]
Merge datasets: transportation availability? 
- Within xxx radius, how many transportation stations are available

**Comment by yukewang1** [comment]
Merge dataset: population data
- More people in the area suggests more potential biking activity

**Comment by yukewang1** [comment]
Merge dataset: bikeways
https://opendata.vancouver.ca/explore/dataset/bikeways/information/?disjunctive.bike_route_name&disjunctive.bikeway_type&disjunctive.year_of_construction&sort=bike_route_name&location=14,49.23144,-123.11181

**Comment by yukewang1** [comment]
Merge dataset: parks
https://opendata.vancouver.ca/explore/dataset/parks/table/?location=17,49.23622,-123.13014
